# Generated by Django 3.2.9 on 2022-02-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='image')),
                ('img2', models.ImageField(upload_to='image')),
                ('img3', models.ImageField(upload_to='image')),
                ('img4', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=255)),
                ('catergory_name', models.CharField(max_length=255)),
                ('narx', models.IntegerField()),
                ('reting', models.IntegerField()),
                ('discriptions', models.TextField()),
                ('productId', models.IntegerField()),
                ('delivery', models.CharField(max_length=255)),
            ],
        ),
    ]
