# Generated by Django 3.2.9 on 2022-02-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_best_selling_product_brend_browse_catergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
