# Generated by Django 3.2.9 on 2022-02-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brend_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=255)),
                ('narx', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Arivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=255)),
                ('narx', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Top_Rated_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=255)),
                ('narx', models.IntegerField()),
            ],
        ),
    ]
