# Generated by Django 3.2.9 on 2022-02-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
    ]
