# Generated by Django 3.2.9 on 2022-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=255)),
            ],
        ),
    ]
