# Generated by Django 3.2.9 on 2022-02-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_single_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_sms',
            old_name='coment',
            new_name='comment',
        ),
    ]
