# Generated by Django 3.2.9 on 2022-02-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_coment_single_sms_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our', models.CharField(max_length=255)),
                ('story', models.TextField()),
            ],
        ),
    ]
